# Generated by Django 2.2.24 on 2021-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=50)),
                ('acreage', models.CharField(max_length=50)),
                ('housetype_list', models.CharField(max_length=100)),
                ('average_price', models.IntegerField()),
                ('total_price', models.CharField(max_length=20)),
                ('advantage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Renting_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('brif_introduction', models.CharField(max_length=100)),
                ('advantage', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondHouse_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('houseinfo', models.CharField(max_length=100)),
                ('totalPrice', models.CharField(max_length=20)),
                ('unitPrice', models.IntegerField()),
            ],
        ),
    ]
