# Generated by Django 2.2.24 on 2021-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Buy_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('house_type', models.IntegerField()),
                ('expected_price_max', models.IntegerField()),
                ('expected_price_min', models.IntegerField()),
                ('adress1', models.CharField(max_length=10)),
                ('adress2', models.CharField(max_length=40)),
                ('requirement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Rent_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rent_type', models.IntegerField()),
                ('expected_price_max', models.IntegerField()),
                ('expected_price_min', models.IntegerField()),
                ('adress1', models.CharField(max_length=10)),
                ('adress2', models.CharField(max_length=40)),
                ('requirement', models.CharField(max_length=50)),
            ],
        ),
    ]
