# Generated by Django 2.2.24 on 2021-08-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesit', '0002_request_buy_info_request_rent_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_buy_info',
            name='post_data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request_rent_info',
            name='post_data',
            field=models.DateField(auto_now=True),
        ),
    ]
