# Generated by Django 2.2.24 on 2021-08-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managesit', '0005_admin_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_info',
            old_name='name',
            new_name='username',
        ),
    ]
