# Generated by Django 2.2.24 on 2021-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesit', '0006_auto_20210807_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building_info',
            name='acreage',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='building_info',
            name='adress',
            field=models.CharField(default='武昌/武汉理工', max_length=50),
        ),
        migrations.AlterField(
            model_name='building_info',
            name='advantage',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='building_info',
            name='average_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building_info',
            name='housetype_list',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='building_info',
            name='name',
            field=models.CharField(default='无', max_length=30),
        ),
        migrations.AlterField(
            model_name='building_info',
            name='total_price',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='renting_info',
            name='advantage',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='renting_info',
            name='brif_introduction',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='renting_info',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='renting_info',
            name='title',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='request_buy_info',
            name='adress1',
            field=models.CharField(default='武昌', max_length=10),
        ),
        migrations.AlterField(
            model_name='request_buy_info',
            name='adress2',
            field=models.CharField(default='武汉理工', max_length=40),
        ),
        migrations.AlterField(
            model_name='request_buy_info',
            name='expected_price_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request_buy_info',
            name='expected_price_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request_buy_info',
            name='house_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request_buy_info',
            name='name',
            field=models.CharField(default='无', max_length=30),
        ),
        migrations.AlterField(
            model_name='request_buy_info',
            name='requirement',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='request_rent_info',
            name='adress1',
            field=models.CharField(default='武昌', max_length=10),
        ),
        migrations.AlterField(
            model_name='request_rent_info',
            name='adress2',
            field=models.CharField(default='武汉理工', max_length=40),
        ),
        migrations.AlterField(
            model_name='request_rent_info',
            name='expected_price_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request_rent_info',
            name='expected_price_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request_rent_info',
            name='name',
            field=models.CharField(default='无', max_length=30),
        ),
        migrations.AlterField(
            model_name='request_rent_info',
            name='rent_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request_rent_info',
            name='requirement',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='secondhouse_info',
            name='adress',
            field=models.CharField(default='武昌/武汉理工', max_length=100),
        ),
        migrations.AlterField(
            model_name='secondhouse_info',
            name='houseinfo',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='secondhouse_info',
            name='title',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='secondhouse_info',
            name='totalPrice',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AlterField(
            model_name='secondhouse_info',
            name='unitPrice',
            field=models.IntegerField(default=0),
        ),
    ]
